"""report.py — render one app's intel to a self-contained HTML deliverable.

The artifact the user actually opens (the skill's final step). Presentation
only: every number is read from the local DB / the estimator envelope and shown
verbatim with its confidence, method, and flags — this module computes nothing
and can therefore never fabricate. Estimates render as RANGES (never > MEDIUM);
missing data renders as "no data", not a guess. Carries the config-gated
contribution banner (the nudge lives on the artifact, not in run output).
"""
from __future__ import annotations

from html import escape

from .estimate import estimate_app
from .reminders import contribution_enabled, contribution_html

_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — AppScope report</title>
<style>
  :root {{ --bg:#0b0f14; --card:#141b24; --ink:#e6edf3; --mut:#8b98a5; --line:#222d3a; }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; background:var(--bg); color:var(--ink);
         font:15px/1.55 system-ui,-apple-system,Segoe UI,Roboto,sans-serif; }}
  header {{ padding:28px 24px; border-bottom:1px solid var(--line); }}
  h1 {{ margin:0 0 6px; font-size:22px; }}
  .prov {{ color:var(--mut); font-size:13px; }}
  .wrap {{ max-width:900px; margin:0 auto; padding:24px; }}
  .card {{ background:var(--card); border:1px solid var(--line); border-radius:12px;
          padding:18px 20px; margin:0 0 18px; }}
  h2 {{ font-size:17px; margin:0 0 10px; }}
  table {{ width:100%; border-collapse:collapse; font-size:14px; }}
  th, td {{ text-align:left; padding:8px 10px; border-bottom:1px solid var(--line); vertical-align:top; }}
  th {{ color:var(--mut); font-size:12px; text-transform:uppercase; letter-spacing:.6px; }}
  .conf-HIGH {{ color:#56d364; }} .conf-MEDIUM {{ color:#e8c66b; }}
  .conf-LOW {{ color:#f0883e; }} .conf-NONE {{ color:#f85149; }}
  .flag {{ color:#f0883e; font-size:12px; }}
  footer {{ color:var(--mut); font-size:12px; padding:18px 24px; border-top:1px solid var(--line); }}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <div class="prov">{subtitle}</div>
  <div class="prov">Every number below carries its confidence, method, and flags.
  Estimates are ranges and never exceed MEDIUM; observed facts are HIGH; missing data says so.</div>
</header>
<div class="wrap">
{contrib}
{body}
</div>
<footer>Generated by AppScope (self-hosted, local data only) · code MIT, data CC-BY-4.0.
Dollar ad spend and panel-grade installs are never modeled — see the honesty rules in the README.</footer>
</body>
</html>
"""


def _esc(x: object) -> str:
    return escape(str(x)) if x is not None else ""


def _row(label: str, value: str, conf: str = "", method: str = "", flags: str = "") -> str:
    conf_html = f'<td class="conf-{_esc(conf)}">{_esc(conf)}</td>' if conf else "<td></td>"
    return (f"<tr><td>{_esc(label)}</td><td>{value}</td>{conf_html}"
            f"<td>{_esc(method)}</td><td class='flag'>{_esc(flags)}</td></tr>")


def build_report(db, cfg, app_id: str, country: str = "us",
                 out_path: str = "app-intel-report.html") -> str:
    app = db.get_app(app_id) or {}
    latest = db.get_latest_rank(app_id, country=country) or {}
    reviews = db.get_reviews(app_id, days=30)
    buckets = db.get_install_buckets(app_id)
    est = estimate_app(db, app_id, country=country, config=cfg)

    rows: list[str] = []
    if latest.get("rank") is not None:
        rows.append(_row(
            f"Latest rank ({_esc(latest.get('list_type'))}, {country})",
            f"#{_esc(latest.get('rank'))} on {_esc(latest.get('captured_on'))}",
            "HIGH", "local_observed"))
    else:
        rows.append(_row(f"Latest rank ({country})", "no data", "NONE", "not_collected"))

    if buckets:
        b = buckets[-1]
        rows.append(_row(
            "Install bucket (Android, observed)",
            f"min {_esc(b.get('min_installs'))} / real {_esc(b.get('real_installs'))} "
            f"on {_esc(b.get('captured_on'))}",
            "HIGH", "google_play_bucket"))

    if est.get("value") is not None:
        rows.append(_row(
            "Monthly downloads (estimate)",
            f"{_esc(est.get('value'))} (band {_esc(est.get('low'))}–{_esc(est.get('high'))})",
            _esc(est.get("confidence")), _esc(est.get("method")),
            ", ".join(est.get("flags") or [])))
    else:
        rows.append(_row("Monthly downloads (estimate)", "no data — segment uncalibrated",
                         _esc(est.get("confidence", "NONE")), _esc(est.get("method", "uncalibrated")),
                         ", ".join(est.get("flags") or [])))

    rev = est.get("revenue")
    if isinstance(rev, dict) and rev.get("value") is not None:
        rows.append(_row(
            "Monthly revenue (estimate)",
            f"${_esc(rev.get('value'))} (band ${_esc(rev.get('low'))}–${_esc(rev.get('high'))})",
            _esc(rev.get("confidence")), _esc(rev.get("method")),
            ", ".join(rev.get("flags") or [])))
    else:
        rows.append(_row("Monthly revenue (estimate)", "not modeled for this app",
                         "NONE", "refused_or_uncalibrated"))

    rows.append(_row("Reviews captured (last 30 days)", str(len(reviews)), "HIGH", "local_observed"))

    body = (
        '<div class="card"><h2>Intel — with provenance</h2>'
        "<table><tr><th>Metric</th><th>Value</th><th>Confidence</th><th>Method</th>"
        "<th>Flags</th></tr>" + "".join(rows) + "</table></div>"
    )

    contrib = ""
    if contribution_enabled(cfg):
        contrib = contribution_html(getattr(cfg.federation, "dataset_repo", ""))

    name = app.get("name") or app_id
    subtitle_bits = [b for b in (app.get("developer"), app.get("platform"),
                                 app.get("category")) if b]
    page = _PAGE.format(
        title=_esc(name),
        subtitle=_esc(" · ".join(str(b) for b in subtitle_bits)),
        contrib=contrib,
        body=body,
    )
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(page)
    return out_path
